class FollowStatus:
    NOT_FOLLOWING = 'NOT_FOLLOWING'
    FOLLOWING = 'FOLLOWING'
    SELF = 'SELF'
    REQUESTED = 'REQUESTED'
    DENIED = 'DENIED'

    _ALL = (NOT_FOLLOWING, FOLLOWING, SELF, REQUESTED, DENIED)
