class GqlNotificationType:
    POST_COMPLETED = 'POST_COMPLETED'
    POST_ERROR = 'POST_ERROR'
    USER_CHATS_WITH_UNVIEWED_MESSAGES_COUNT_CHANGED = 'USER_CHATS_WITH_UNVIEWED_MESSAGES_COUNT_CHANGED'
    USER_FEED_CHANGED = 'USER_FEED_CHANGED'
    USER_FEED_POST_ADDED = 'USER_FEED_POST_ADDED'
    USER_FOLLOWED_USERS_WITH_STORIES_CHANGED = 'USER_FOLLOWED_USERS_WITH_STORIES_CHANGED'
